name: Generate Snake Game

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.2.0
        with:
          github_user: ${{ github.repository_owner }}
          output: 'snake.svg' # Output file name
          color: '#00ff00' # Customize the color if needed
          # You can add more options here as needed

      - name: Upload Snake Game
        uses: actions/upload-artifact@v2
        with:
          name: snake-game
          path: snake.svg
